next(1) "git.sr.ht/~shinyzenith/NextWM" "General Commands Manual"

# NAME

NextWM - Wayland compositing window manager.

# SYNOPSIS

*next* [_flags_]

# DESCRIPTION

*NextWM* is a wayland compositing window manager written in Zig.

# OPTIONS

TODO

# AUTHORS

Maintained by Shinyzenith <aakashsensharma@gmail.com>.
For more information about development, see <https://git.sr.ht/~shinyzenith/NextWM>.
